networks:
  proxy-network:
    external: true

services:
  matcuka-svelte:
    build: .
    image: matcuka-svelte
    container_name: matcuka_svelte
    ports:
      - 4173:4173
    restart: unless-stopped
    networks:
      - proxy-network