services:
  matcuka_svelte:
    build: .
    image: ivanmatcuka/matcuka_svelte
    container_name: matcuka_svelte
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - matcuka_svelte_network

  matcuka_tunnel:
    image: matcuka_tunnel
    env_file:
      - .env
    container_name: matcuka_tunnel
    restart: unless-stopped
    networks:
      - matcuka_svelte_network

networks:
  matcuka_svelte_network:
    driver: bridge