networks:
  proxy-network:
    external: true

services:
  matcuka_svelte:
    build: .
    image: matcuka-svelte
    container_name: matcuka_svelte
    ports:
      - 4175:4173
    restart: unless-stopped
    networks:
      - proxy-network

  matcuka_tunnel:
    image: matcuka_tunnel
    env_file:
      - .env
    container_name: matcuka_tunnel
    restart: unless-stopped
    networks:
      - proxy-network
