services:
  matcuka_svelte:
    build:
      context: .
      args:
        PUBLIC_API_URL: ${PUBLIC_API_URL}
        PUBLIC_CMS_URL: ${PUBLIC_CMS_URL}
    image: ivanmatcuka/matcuka_svelte
    container_name: matcuka_svelte
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - matcuka-svelte-network

  matcuka_tunnel:
    image: matcuka_tunnel
    env_file:
      - .env
    container_name: matcuka_tunnel
    restart: unless-stopped
    networks:
      - matcuka-svelte-network

networks:
  matcuka-svelte-network:
    driver: bridge
