networks:
  proxy-network:
    external: true

services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: matcuka-strapi-dev
    container_name: matcuka_strapi
    ports:
      - 1338:1337
    environment:
      - NODE_ENV=development
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
      - ./.tmp/data.db:/opt/app/.tmp/data.db
    restart: unless-stopped
    networks:
      - proxy-network

  strapi_tunnel:
    build:
      context: .
      dockerfile: Dockerfile.tunnel
      args:
        TUNNEL_SUBDOMAIN: ${TUNNEL_SUBDOMAIN}
        TUNNEL_SERVER: ${TUNNEL_SERVER}
        TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    env_file:
      - .env
    container_name: strapi_tunnel
    restart: unless-stopped
    networks:
      - proxy-network
