services:
  matcuka_strapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ivanmatcuka/matcuka_strapi
    container_name: matcuka_strapi
    environment:
      - NODE_ENV=development
    ports:
      - '1337:1337'
    restart: unless-stopped
    networks:
      - matcuka_strapi_network
    volumes:
      - matcuka-strapi-db:/opt/app/.tmp/data.db

  strapi_tunnel:
    image: matcuka_tunnel
    env_file:
      - .env
    container_name: strapi_tunnel
    restart: unless-stopped
    networks:
      - matcuka_strapi_network

networks:
  matcuka_strapi_network:
    driver: bridge

volumes:
  matcuka-strapi-db: